# This is a basic workflow to help you get started with Actions

name: PKGBUILD workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test_github_actions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build pkgs-builder Docker image
      - name: Build pkgs-builder Docker image
        run: |
          docker build -t pkgs-builder ./pkgs-builder

      # pkgbuild 
      - name: Create pkgs
        run: |
          for pkgdir in $(find . -type f -name PKGBUILD -exec dirname {} \;); do
            echo "=== Building $pkgdir ==="
            docker run --rm -u 1000 \
            -v "$PWD/$pkgdir":/home/bobthebuilder/build \
            pkgs-builder \
            bash -c "makepkg -sf --noconfirm"
          done